[tool.pdm]
[tool.pdm.dev-dependencies]
dev = [
    "uvicorn>=0.21.0",
]

[project]
name = "FastCLAM"
version = "0.0.1"
description = "FastAPI for CLAMS"
authors = [
    {name = "WGBH-MLA", email = "ryan_harbert@wgbh.org"},
]
dependencies = [
    "fastapi>=0.94.0",
    "pydantic>=1.10.6",
    "clams-python>=0.5.2",
]
requires-python = ">=3.10"
license = {text = "MIT"}
