[tool.poetry]
name = "FastCLAM"
version = "0.0.1"
description = "FastAPI for CLAMS Applications"
authors = ["WGBH-MLA"]
readme = "README.md"
packages = [{include = "fastclam"}]

[tool.poetry.dependencies]
python = "^3.8"
clams-python = "^0.5.2"
mmif-python = "^0.4.2"
pydantic = "^1.8.2"
fastapi = "^0.94.0"
loguru = "^0.6.0"
rich = "^13.3.2"


[tool.poetry.group.test.dependencies]
uvicorn = "^0.21.0"


[tool.poetry.group.dev.dependencies]
pytest = "^7.2.2"
httpx = "^0.23.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
